### ISSUE TITLE
Pagination of collections

### ISSUE THREAD

**Issue by beowulfenator** [grnhse/greenhouse-tools-php#14]
In the API description there is a mention of [RFC-5988 link headers](https://developers.greenhouse.io/harvest.html#pagination) and a very reasonable recommendation to "not page manually by changing the paging-related query parameters".

This library, however, encourages to do just that (set the "page" parameter manually). Also, there seems to be no mechanism to determine how many pages the result set has in total.

What is the preferred way to iterate over a large collection with this library?

**Comment by tdphillipsjr** [comment]
Addressed in https://github.com/grnhse/greenhouse-tools-php/releases/tag/v1.3.2

Which creates a `$harvestService->nextLink();` method.

**Comment by alexmarek** [comment]
Hi, can I be removed form this mailing list please. No idea how I ended up here. Thanks.

**Comment by tdphillipsjr** [comment]
Hi @alexmarek - you set yourself as a watcher on this repo. I can't remove you, but you can remove yourself here: https://github.com/grnhse/greenhouse-tools-php/watchers
