### ISSUE TITLE
Add support for other PHP HTTP Clients via HTTPlug

### ISSUE THREAD

**Issue by zaporylie** [grnhse/greenhouse-tools-php#18]
Unfortunately this package has a hard requirement in Guzzle. Please consider switching over to https://github.com/php-http/httplug and enable application using this package for injecting their own, PSR7 compatible http clients.

**Comment by tdphillipsjr** [comment]
Hi. We're happy to accept pull requests for other packages. The only requirement is they must adhere to the provided interface.

https://github.com/grnhse/greenhouse-tools-php/blob/master/src/Clients/ApiClientInterface.php
