### ISSUE TITLE
[Job board API] Not able to post answer objects like demographic_answers, educations and so on. | Missing functionality for posting objects.

### ISSUE THREAD

**Issue by sachinkumar121** [grnhse/greenhouse-tools-php#23]
- PHP version:- 7.3.7
- Package version:- 1.3.3

**Description:**
It seems that there is some missing functionality for posting the object from the form. So that why we are not able to post the demographic_answers, educations, and employments objects when we post the job application to the Job board.

As the "formatPostParameters" function in GuzzleClient.php file can only post the multi-select data which are flattened.
https://github.com/grnhse/greenhouse-tools-php/blob/master/src/Clients/GuzzleClient.php#L104

So let say we have the form with the following element

    <input type="hidden" name="demographic_answers[][question_id]" value="87" />
    <input type="hidden" name="demographic_answers[][answer_options][][answer_option_id]" value="194" />
    <label><input type="checkbox" name="question_2222[]" value="2" /> Red</label><br/>
    <label><input type="checkbox" name="question_2222[]" value="5" /> Orange</label>

Now this formatPostParameters function will convert the parameters as follow.

    Array
    (
        // ... other post element.
        [18] => Array
            (
                [name] => demographic_answers[]
                [contents] => Array
            )

        [19] => Array
            (
                [name] => demographic_answers[]
                [contents] => Array
            )

        [22] => Array
            (
                [name] => question_2222[]
                [contents] => 2
            )

        [23] => Array
            (
                [name] => question_2222[]
                [contents] => 5
            )

    )

### Steps To Reproduce

- Create the job application form element with mention elements
- submit the job application and you will get **"400 Bad Request"** error response and "Candidate not saved"

**Comment by acaloiaro** [comment]
Hi @sachinkumar121, thanks for the detailed report. This was reported to Greenhouse by a customer internally as well. 

I've attached a pull request that is in the process of being reviewed and we'll cut a release as soon as it's through review. 

Cheers,
AC
