### ISSUE TITLE
Mistake in Example

### ISSUE THREAD

**Issue by Nik-ADA** [grnhse/greenhouse-tools-php#3]
https://github.com/grnhse/greenhouse-tools-php#the-application-service

You written: `$appService = $greenhouseService->getApplicationService();`
For Me gives error.

I guess correctly: `$appService = $greenhouseService->getApplicationApiService();`
so works

**Comment by tdphillipsjr** [comment]
Thanks!  This has been changed.

https://github.com/grnhse/greenhouse-tools-php/commit/4ca41648f6bf89913ee92ba6977c93bfbd271e2b
