### ISSUE TITLE
parse_header() has been replaced with Header::parse()

### ISSUE THREAD

**Issue by jameelmoses** [grnhse/greenhouse-tools-php#37]
When trying to access `getJobApiService` after the recent release, I'm getting the following error:

`Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\Psr7\parse_header() in vendor/grnhse/greenhouse-tools-php/src/Clients/GuzzleClient.php:155`

This is as a result of a call to `parse_header()`, which has been replaced with `Header::parse()`. See [here](https://github.com/guzzle/psr7#upgrading-from-function-api).

**Comment by tdphillipsjr** [comment]
Added and released as 2.1.3
