### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by Nik-ADA** [grnhse/greenhouse-tools-php#5]
I would add a response from respons in postApplication

https://github.com/grnhse/greenhouse-tools-php/blob/c98fe6a7f2e94a82e24f7056010a34ac7a2b4ba1/src/Services/ApplicationService.php#L79

**Comment by tdphillipsjr** [comment]
I'm not exactly sure what you'd be looking for out of a successful response.  The contract here is "if it doesn't throw an exception, it was successful."

If you'd like to submit a pull request making this change, we'd consider it.
